'''
Here is where the variables go.
'''

# Variables--
# ADJECTIVE_STORE       *
# STORE_TYPE            *
# OTHER_NEIGHBOURGOOD   *
# ADJECTIVE_ITEM        *
# ITEM                  *
# NATIONALITY           *
# DISPLAY_TYPE          *

ADJECTIVE_STORE = [
    "new",
    "vintage",
    "reopened",
    "pop-up",
    "foreclosed",
    "famous",
    "$nationality"
]

ADJECTIVE_ITEM = [
    "big",
    "colossal",
    "petite",
    "scrawny",
    "small",
    "tall",
    "teeny-tiny",
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "purple",
    "gray",
    "black",
    "white",
    "adorable",
    "fancy",
    "magnificent",
    "quaint",
    "sparkling",
    "broken",
    "bumpy",
    "cuddly",
    "fluffy",
    "hot",
    "warm",
    "wet",
    "delightful",
    "gentle",
    "lively",
    "silly"
]

DISPLAY_TYPE = [
    "a rare",
    "a broken",
    "a $300",
    "a brand new",
]

DISPLAY_TYPE_P = [
    "full of",
    "twin",
    "several small",
    "four"
]

STORE_TYPE = [
    "!animal hospital",
    "!art supply store",
    "!auto centre",
    "bank",
    "bar",
    "barber",
    "beauty salon",
    "board game cafe",
    "bookkeeper",
    "charcuterie",
    "children's clothing store",
    "chiropractor",
    "chocolatier",
    "church",
    "coin laundry",
    "condo development",
    "coworking space",
    "craft brewery",
    "dentist",
    "design studio",
    "doggy daycare",
    "florist",
    "frozen yogurt cafe",
    "funeral home",
    "furniture store",
    "gym",
    "halfway house",
    "health centre",
    "herbal dispensary",
    "indoor playground",
    "juice bar",
    "kitchen designer",
    "massage therapist",
    "music teacher",
    "naturopath",
    "!optometrist",
    "!orthopedic store",
    "paint store",
    "parkette",
    "payday loan store",
    "pizza chain",
    "pool hall",
    "portrait studio",
    "realtor",
    "sandwich chain",
    "school",
    "specialist grocer",
    "stationer",
    "tailor",
    "used bookstore",
    "variety store",
    "vegan bakery",
    "vintage retailer",
    "yoga studio"
]

OTHER_NEIGHBOURHOOD = [
    "Cabbagetown",
    "CityPlace",
    "Corktown",
    "East Bayfront",
    "Grange Park",
    "Moss Park",
    "St. Lawrence",
    "Toronto Islands",
    "Yorkville",
    "Casa Loma",
    "Davisville",
    "Moore Park",
    "Wychwood Park",
    "Midtown",
    "Corso Italia",
    "Earlscourt",
    "Liberty Village",
    "Parkdale",
    "East Danforth",
    "Leaside",
    "Thorncliffe Park",
    "Alderwood",
    "Long Branch",
    "Rexdale",
    "Richview",
    "Sunnylea",
    "Thorncrest Village",
    "Willowridge",
    "Agincourt",
    "Bendale",
    "Cliffside",
    "Ionview",
    "L'Amoreaux",
    "Morningside",
    "Rouge",
    "Tam O'Shanter",
    "West Hill",
    "Black Creek",
    "Don Mills",
    "Downsview",
    "Glen Park",
    "Humber Summit",
    "Lansing",
    "Newtonbrook",
    "The Peanut",
    "Willowdale",
    "Weston",
    "Mount Dennis"
]

ITEM = [
    "CD",
    "Christmas ornament",
    "!acorn",
    "!apple",
    "bag",
    "bag of cotton balls",
    "bag of popcorn",
    "bag of rubber bands",
    "ball of yarn",
    "balloon",
    "banana",
    "bandana",
    "bangle bracelet",
    "bar of soap",
    "baseball",
    "baseball bat",
    "baseball hat",
    "basketball",
    "beaded bracelet",
    "beaded necklace",
    "bed",
    "beef",
    "bell",
    "belt",
    "blouse",
    "blowdryer",
    "bonesaw",
    "book",
    "book of jokes",
    "book of matches",
    "bookmark",
    "boom box",
    "bottle",
    "bottle cap",
    "bottle of glue",
    "bottle of honey",
    "bottle of ink",
    "bottle of lotion",
    "bottle of nail polish",
    "bottle of oil",
    "bottle of paint",
    "bottle of perfume",
    "bottle of pills",
    "bottle of soda",
    "bottle of sunscreen",
    "bottle of syrup",
    "bottle of water",
    "bouquet of flowers",
    "bow",
    "bow tie",
    "bowl",
    "box",
    "box of Q-tips",
    "box of baking soda",
    "box of chalk",
    "box of chocolates",
    "box of crayons",
    "box of markers",
    "box of tissues",
    "bracelet",
    "bread",
    "broccoli",
    "brush",
    "buckle",
    "butter knife",
    "button",
    "camera",
    "can of beans",
    "can of chili",
    "can of peas",
    "can of whipped cream",
    "candle",
    "candlestick",
    "candy bar",
    "candy cane",
    "candy wrapper",
    "canteen",
    "canvas",
    "car",
    "card",
    "carrot",
    "cars",
    "carton of ice cream",
    "cat",
    "catalogue",
    "cell phone",
    "cement stone",
    "chain",
    "chair",
    "chalk",
    "chapter book",
    "cheque book",
    "chenille stick",
    "chicken",
    "children's book",
    "chocolate",
    "class ring",
    "clay pot",
    "clock",
    "clothes",
    "clothes pin",
    "coffee mug",
    "coffee pot",
    "comb",
    "comic book",
    "computer",
    "conditioner",
    "container of pudding",
    "cookie jar",
    "cookie tin",
    "cork",
    "couch",
    "cow",
    "cowboy hat",
    "craft book",
    "credit card",
    "crow",
    "crowbar",
    "cucumber",
    "cup",
    "dagger",
    "deodorant ",
    "desk",
    "dictionary",
    "dog",
    "dolphin",
    "domino set",
    "door",
    "dove",
    "drawer",
    "drill press",
    "!egg",
    "!egg beater",
    "!egg timer",
    "!empty bottle",
    "!empty jar",
    "!empty tin can",
    "!eraser",
    "!extension cord",
    "!eye liner",
    "face wash",
    "fake flowers",
    "feather",
    "feather duster",
    "fish",
    "fishing hook",
    "flag",
    "flashlight",
    "floor",
    "bunch of flowers",
    "flyswatter",
    "food",
    "football",
    "fork",
    "fridge",
    "frying pan",
    "game CD",
    "game cartridge",
    "garden spade",
    "giraffe",
    "glass",
    "glasses",
    "glow stick",
    "grid paper",
    "grocery list",
    "hair brush",
    "hair clip",
    "hair pin",
    "hair ribbon",
    "hair tie",
    "hammer",
    "hamster",
    "hand bag",
    "hand fan",
    "hand mirror",
    "handbasket",
    "handful of change",
    "handheld game system",
    "hanger",
    "harmonica",
    "helmet",
    "house",
    "!ice cream stick",
    "!ice cube",
    "!ice pick",
    "!incense holder",
    "!ipod",
    "!ipod charger",
    "jar of jam",
    "jar of peanut butter",
    "jar of pickles",
    "jigsaw puzzle",
    "key",
    "key chain",
    "keyboard",
    "keychain",
    "keys",
    "kitchen knife",
    "knife",
    "lace",
    "ladle",
    "lamp",
    "lamp shade",
    "laser pointer",
    "leg warmers",
    "lemon",
    "letter opener",
    "light",
    "light bulb",
    "lighter",
    "lime",
    "lion",
    "lip gloss",
    "locket",
    "tub of lotion",
    "magazine",
    "magnet",
    "magnifying glass",
    "map",
    "marble",
    "martini glass",
    "matchbook",
    "microphone",
    "milk",
    "miniature portrait",
    "mirror",
    "mobile phone",
    "model car",
    "monitor",
    "mop",
    "mouse pad",
    "mp3 player",
    "multitool",
    "music CD",
    "nail",
    "nail clippers",
    "nail filer",
    "necktie",
    "needle",
    "notebook",
    "notepad",
    "novel",
    "!ocarina",
    "!orange",
    "!outlet",
    "pack of cards",
    "package of crisp and crunchy edibles",
    "package of glitter",
    "packet of seeds",
    "pail",
    "paintbrush",
    "pair of binoculars",
    "pair of dice",
    "pair of earrings",
    "pair of glasses",
    "pair of handcuffs",
    "pair of knitting needles",
    "pair of rubber gloves",
    "pair of safety goggles",
    "pair of scissors",
    "pair of socks",
    "pair of sunglasses",
    "pair of tongs",
    "pair of water goggles",
    "panda",
    "pair of pants",
    "paper",
    "paperclip",
    "pasta strainer",
    "pearl necklace",
    "pen",
    "pencil",
    "pencil holder",
    "pepper shaker",
    "perfume",
    "phone",
    "photo album",
    "picture frame",
    "piece of gum",
    "pillow",
    "pinecone",
    "plastic fork",
    "plate",
    "plush bear",
    "plush cat",
    "plush dinosaur",
    "plush dog",
    "plush frog",
    "plush octopus",
    "plush pony",
    "plush rabbit",
    "plush unicorn",
    "pocketknife",
    "pocketwatch",
    "pool stick",
    "pop can",
    "postage stamp",
    "puddle",
    "purse",
    "quartz crystal",
    "quilt",
    "rabbit",
    "radio",
    "rat",
    "remote",
    "rhino",
    "ring",
    "rock",
    "roll of duct tape",
    "roll of gauze",
    "roll of masking tape",
    "roll of stickers",
    "roll of toilet paper",
    "rolling pin",
    "rope",
    "rubber band",
    "rubber duck",
    "rubber stamp",
    "rug",
    "rusty nail",
    "safety pin",
    "sailboat",
    "salt shaker",
    "sand paper",
    "sandal",
    "sandglass",
    "scallop shell",
    "scarf",
    "scotch tape",
    "screw",
    "screwdriver",
    "seat belt",
    "shampoo",
    "shark",
    "sharpie",
    "shawl",
    "sheep",
    "sheet of paper",
    "shirt",
    "shirt button",
    "shoe lace",
    "pair of shoes",
    "shopping bag",
    "shovel",
    "sidewalk",
    "sketch pad",
    "slipper",
    "small pouch",
    "snail shell",
    "snowglobe",
    "soap",
    "soccer ball",
    "socks",
    "sofa",
    "spatula",
    "speakers",
    "pair of spectacles",
    "spice bottle",
    "sponge",
    "spool of ribbon",
    "spool of string",
    "spool of thread",
    "spool of wire",
    "spoon",
    "spring",
    "squirrel",
    "squirt gun",
    "statuette",
    "steak knife",
    "stick",
    "stick of incense",
    "sticker book",
    "sticky note",
    "stockings",
    "stop sign",
    "straw",
    "street light",
    "pair of sun glasses",
    "sword",
    "table",
    "tea cup",
    "tea pot",
    "teddies",
    "television",
    "tennis ball",
    "tennis racket",
    "thermometre",
    "thimble",
    "thread",
    "tiger",
    "tire swing",
    "tissue box",
    "toe ring",
    "toilet",
    "toilet paper tube",
    "tomato",
    "tooth pick",
    "toothbrush",
    "toothpaste",
    "toothpick",
    "towel",
    "toy boat",
    "toy car",
    "toy plane",
    "toy robot",
    "toy soldier",
    "toy top",
    "trash bag",
    "tree",
    "trucks",
    "tube of lip balm",
    "tube of lipstick",
    "turtle",
    "tv",
    "twister",
    "!umbrella",
    "vase",
    "video games",
    "wallet",
    "washcloth",
    "washing machine",
    "watch",
    "water bottle",
    "wedding ring",
    "whale",
    "whip",
    "whistle",
    "window",
    "wine glass",
    "wireless control",
    "wishbone",
    "wooden spoon",
    "word search",
    "wrench",
    "wristwatch",
    "zebra",
    "zipper"]

ITEMS = [
    "CDs",
    "Christmas ornaments",
    "acorns",
    "apples",
    "bags",
    "bags of cotton balls",
    "bags of popcorn",
    "bags of rubber bands",
    "balls of yarn",
    "balloons",
    "bananas",
    "bandanas",
    "bangle bracelets",
    "bars of soap",
    "baseballs",
    "baseball bats",
    "baseball hats",
    "basketballs",
    "beaded bracelets",
    "beaded necklaces",
    "beds",
    "bells",
    "belts",
    "blouses",
    "blowdryers",
    "bonesaws",
    "books",
    "books of jokes",
    "books of matches",
    "bookmarks",
    "boom boxes",
    "bottles",
    "bottle caps",
    "bottles of glue",
    "bottles of honey",
    "bottles of ink",
    "bottles of lotion",
    "bottles of nail polish",
    "bottles of oil",
    "bottles of paint",
    "bottles of perfume",
    "bottles of pills",
    "bottles of soda",
    "bottles of sunscreen",
    "bottles of syrup",
    "bottles of water",
    "bouquets of flowers",
    "bows",
    "bow ties",
    "bowls",
    "boxes",
    "boxes of Q-tips",
    "boxes of baking soda",
    "boxes of chalk",
    "boxes of chocolates",
    "boxes of crayons",
    "boxes of markers",
    "boxes of tissues",
    "bracelets",
    "breads",
    "broccolis",
    "brushes",
    "buckles",
    "butter knives",
    "buttons",
    "cameras",
    "cans of beans",
    "cans of chili",
    "cans of peas",
    "cans of whipped cream",
    "candles",
    "candlesticks",
    "candy bars",
    "candy canes",
    "candy wrappers",
    "canteens",
    "canvasses",
    "cards",
    "carrots",
    "cars",
    "cartons of ice cream",
    "cats",
    "catalogues",
    "cement stones",
    "chains",
    "chairs",
    "chalks",
    "chapter books",
    "cheque books",
    "chenille sticks",
    "chickens",
    "children's books",
    "chocolates",
    "class rings",
    "clay pots",
    "clocks",
    "clothes",
    "clothes pins",
    "coffee mugs",
    "coffee pots",
    "combs",
    "comic books",
    "computers",
    "conditioners",
    "containers of pudding",
    "cookie jars",
    "cookie tins",
    "corks",
    "couches",
    "cows",
    "cowboy hats",
    "craft books",
    "credit cards",
    "crows",
    "crowbars",
    "cucumbers",
    "cups",
    "daggers",
    "deodorants",
    "desks",
    "dictionarys",
    "dogs",
    "dolphins",
    "domino sets",
    "doors",
    "doves",
    "drawers",
    "drill presses",
    "eggs",
    "egg beaters",
    "egg timers",
    "empty bottles",
    "empty jars",
    "empty tin cans",
    "erasers",
    "extension cords",
    "eye liners",
    "face washes",
    "fake flowers",
    "feathers",
    "feather dusters",
    "fishes",
    "fishing hooks",
    "flags",
    "flashlights",
    "floors",
    "flowers",
    "flyswatters",
    "footballs",
    "forks",
    "fridges",
    "frying pans",
    "game CDs",
    "game cartridges",
    "garden spades",
    "giraffes",
    "glasses",
    "glow sticks",
    "grid papers",
    "grocery lists",
    "hair brushes",
    "hair clips",
    "hair pins",
    "hair ribbons",
    "hair ties",
    "hammers",
    "hamsters",
    "hand bags",
    "hand fans",
    "hand mirrors",
    "handbaskets",
    "handfuls of change",
    "handheld game systems",
    "hangers",
    "harmonicas",
    "helmets",
    "houses",
    "ice cream sticks",
    "ice cubes",
    "ice picks",
    "incense holders",
    "ipods",
    "ipod chargers",
    "jars of jam",
    "jars of peanut butter",
    "jars of pickles",
    "jigsaw puzzles",
    "keys",
    "keyboards",
    "keychains",
    "keys",
    "kitchen knives",
    "knives",
    "laces",
    "ladles",
    "lamps",
    "lamp shades",
    "laser pointers",
    "leg warmers",
    "lemons",
    "letter openers",
    "lights",
    "light bulbs",
    "lighters",
    "limes",
    "lions",
    "lip glosses",
    "lockets",
    "lotions",
    "magazines",
    "magnets",
    "magnifying glasses",
    "maps",
    "marbles",
    "martini glasses",
    "matchbooks",
    "microphones",
    "miniature portraits",
    "mirrors",
    "cellphones",
    "model cars",
    "moneys",
    "monitors",
    "mops",
    "mouse pads",
    "mp3 players",
    "multitools",
    "music CDs",
    "nails",
    "nail filers",
    "neckties",
    "needles",
    "notebooks",
    "notepads",
    "novels",
    "ocarinas",
    "oranges",
    "outlets",
    "packs of cards",
    "packages of crisp and crunchy edibles",
    "packages of glitter",
    "packets of seeds",
    "pails",
    "paintbrushes",
    "pandas",
    "pants",
    "paperclips",
    "pasta strainers",
    "pearl necklaces",
    "pens",
    "pencils",
    "pencil holders",
    "pepper shakers",
    "perfumes",
    "phones",
    "photo albums",
    "picture frames",
    "pieces of gum",
    "pillows",
    "pinecones",
    "plastic forks",
    "plates",
    "plush bears",
    "plush cats",
    "plush dinosaurs",
    "plush dogs",
    "plush frogs",
    "plush octopuses",
    "plush ponies",
    "plush rabbits",
    "plush unicorns",
    "pocketknives",
    "pocketwatches",
    "pool sticks",
    "pop cans",
    "postage stamps",
    "puddles",
    "purses",
    "quartz crystals",
    "quilts",
    "rabbits",
    "radios",
    "rats",
    "remotes",
    "rhinos",
    "rings",
    "rocks",
    "rolls of duct tape",
    "rolls of gauze",
    "rolls of masking tape",
    "rolls of stickers",
    "rolls of toilet paper",
    "rolling pins",
    "ropes",
    "rubber bands",
    "rubber ducks",
    "rubber stamps",
    "rugs",
    "rusty nails",
    "safety pins",
    "sailboats",
    "salt shakers",
    "sandals",
    "sandglasses",
    "scallop shells",
    "scarves",
    "screws",
    "screwdrivers",
    "seat belts",
    "shampoos",
    "sharks",
    "sharpies",
    "shawls",
    "sheep",
    "sheets of paper",
    "shirts",
    "shirt buttons",
    "shoe laces",
    "shoes",
    "shopping bags",
    "shovels",
    "sidewalks",
    "sketch pads",
    "slippers",
    "small pouches",
    "snail shells",
    "snowglobes",
    "soccer balls",
    "socks",
    "sofas",
    "spatulas",
    "speakers",
    "spectacles",
    "spice bottles",
    "sponges",
    "spools of ribbon",
    "spools of string",
    "spools of thread",
    "spools of wire",
    "spoons",
    "springs",
    "squirrels",
    "squirt guns",
    "statuettes",
    "steak knives",
    "sticks",
    "sticks of incense",
    "sticker books",
    "sticky notes",
    "stockings",
    "stop signs",
    "straws",
    "street lights",
    "sun glasses",
    "swords",
    "tables",
    "tea cups",
    "tea pots",
    "teddies",
    "tennis balls",
    "tennis rackets",
    "thermometres",
    "thimbles",
    "threads",
    "tigers",
    "tire swings",
    "tissue boxes",
    "toe rings",
    "toilets",
    "toilet paper tubes",
    "tomatoes",
    "tooth picks",
    "toothbrushes",
    "toothpicks",
    "towels",
    "toy boats",
    "toy cars",
    "toy planes",
    "toy robots",
    "toy soldiers",
    "toy tops",
    "trash bags",
    "trees",
    "trucks",
    "tubes of lip balm",
    "tubes of lipstick",
    "turtles",
    "TVs",
    "tweezers",
    "twisters",
    "umbrellas",
    "vases",
    "video games",
    "wallets",
    "washcloths",
    "washing machines",
    "watches",
    "water bottles",
    "wedding rings",
    "whales",
    "whips",
    "whistles",
    "windows",
    "wine glasses",
    "wireless controls",
    "wishbones",
    "wooden spoons",
    "word searches",
    "wrenches",
    "wristwatches",
    "zebras",
    "zippers"
]

NATIONALITY = [
    "Brazilian",
    "Costa Rican",
    "Honduran",
    "Mexican",
    "Malagasy",
    "Namibian",
    "Ethiopian",
    "Moroccan",
    "Irish",
    "Maltese",
    "French",
    "Austrian",
    "Swedish",
    "Kazakhstani",
    "Russian",
    "Bengali",
    "Japanese",
    "North Korean",
    "Vietnamese",
    "Australian",
    "Indonesian"]